version: "3"
services:
  redis:
    image: "redis"
    restart: "always"
  rabbit:
    image: "rabbitmq:3-management"
    restart: "always"
  bridge:
    build: .
    environment:
      - NODE_ENV=production
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
    command: "true"
    restart: "always"
